In [2]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\Dell\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# load datset
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
# converting from object type to datetime
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [6]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [ ]:
df.sample(10,random_state=42) # random state helps to game same result evry time

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
156941,Data Analyst,Data Analyst,"West Jakarta, West Jakarta City, Jakarta, Indo...",via Glints,Full-time,False,Indonesia,2023-12-13 08:47:03,False,False,Indonesia,NaN,NaN,NaN,PT Stampindo Lancar Jaya,"['python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
90073,Data Analyst,Data Analyst,Anywhere,via Recruit.net,Contractor,True,Switzerland,2023-01-08 00:24:17,False,False,Switzerland,NaN,NaN,NaN,GITR,"['go', 'python', 'spreadsheet', 'git', 'jira']","{'analyst_tools': ['spreadsheet'], 'async': ['..."
490720,Data Analyst,Big Data Engineer / Data Analyst (Azure Data /...,Singapore,via LinkedIn,Full-time,False,Singapore,2023-01-26 11:27:54,False,False,Singapore,NaN,NaN,NaN,Randstad Singapore,['azure'],{'cloud': ['azure']}
123271,Data Engineer,"Director, Data Engineering","Vancouver, BC, Canada",via BeBee Canada,Full-time,False,Canada,2023-12-22 08:20:34,True,False,Canada,NaN,NaN,NaN,Procurify,"['sql', 'nosql', 'mongodb', 'mongodb', 'go', '...","{'analyst_tools': ['tableau'], 'cloud': ['data..."
387186,Data Analyst,Junior Data Analyst,"Budapest, Hungary",via LinkedIn Hungary,Full-time,False,Hungary,2023-01-19 19:19:30,True,False,Hungary,NaN,NaN,NaN,Sony Europe,"['sql', 'sql server', 'sap', 'excel']","{'analyst_tools': ['sap', 'excel'], 'databases..."
330350,Data Engineer,Engineer - Data Management,"Puducherry, India",via The Muse,Full-time,False,India,2023-07-06 23:13:15,False,False,India,NaN,NaN,NaN,Eaton,"['vba', 'oracle', 'sap', 'excel', 'power bi']","{'analyst_tools': ['sap', 'excel', 'power bi']..."
624090,Data Scientist,Data Scientist - FounData,"Søborg, Denmark",via LinkedIn,Full-time,False,Denmark,2023-06-01 13:04:54,False,False,Denmark,NaN,NaN,NaN,Novo Nordisk,"['python', 'r', 'go', 'aws']","{'cloud': ['aws'], 'programming': ['python', '..."
461596,Data Analyst,big data analyst,Canada,via Jobs Trabajo.org,Full-time,False,Canada,2023-12-22 14:20:38,False,False,Canada,NaN,NaN,NaN,FULLAND Logistics Ltd.,"['java', 'python', 'linux', 'windows']","{'os': ['linux', 'windows'], 'programming': ['..."
377637,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-10-02 18:31:08,True,False,United States,NaN,NaN,NaN,Brooksource,"['python', 'sql', 'mongo', 'java', 'scala', 'd...","{'cloud': ['aws', 'redshift', 'aurora'], 'data..."
370750,Senior Data Engineer,Senior Data Engineer (Python/AWS/GCP),"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-11-02 23:09:40,True,False,United States,NaN,NaN,NaN,NTT DATA Services,"['java', 'python', 'aws', 'linux', 'git', 'jen...","{'cloud': ['aws'], 'os': ['linux'], 'other': [..."

In [9]:
# obj index and copy of data
df_original=dataset['train'].to_pandas()
df_altered=df_original

In [12]:
# fill missing values using the median of salary_year_avg
median_salary = df_altered['salary_year_avg'].median()
median_year_salary = df_altered['salary_year_avg'].fillna(median_salary)

In [13]:
id(df_original)==id(df_altered)

True

In [ ]:
df_altered=df_original.copy() # changes id of bith address

In [16]:
id(df_original)==id(df_altered)

False